include = [
    "LM/LM5/mainpanel.toml",
    "LM/LM5/leftpanel.toml",
    "LM/LM5/rightpanel.toml",
    "LM/LM5/ecs.toml"
]

[[panels]]
name = "LeftWindow"
width = 1920
height = 1080
neighbor.up = "LeftZoom"
neighbor.down = "LpdView"
neighbor.left = "LeftPanel"
neighbor.right = "MainPanel"
texture = "lem_left_window.dds"
camera_direction = "forward"
camera_offset_2d.x = -0.576
camera_offset_2d.y = 0.15
camera_offset_2d.z = 1.26

[[panels.objects]]
name = "CWEA2"
pos2d.x = 0
pos2d.y = 0
texture = "lem_cw_lights.dds"

[[panels.objects]]
name = "CWEA3"
pos2d.x = 0
pos2d.y = 0
texture = "lem_cw_lights.dds"

[[panels]]
name = "LeftZoom"
width = 1920
height = 1080
neighbor.down = "LeftWindow"
texture = "lem_left_zoom.dds"
camera_direction = "forward"
fov_override = 30.0
camera_offset_2d.x = -0.576
camera_offset_2d.y = 0.15
camera_offset_2d.z = 1.26

[[panels]]
name = "LpdView"
width = 1920
height = 1080
neighbor.up = "LeftWindow"
texture = "lem_lpd_window.dds"
camera_direction = "lpd"
camera_offset_2d.x = -0.58
camera_offset_2d.y = -0.15
camera_offset_2d.z = 1.40

[[panels.objects]]
name = "CWEA4"
pos2d.x = 0
pos2d.y = 0
texture = "lem_cw_lights.dds"

[[panels]]
name = "RightWindow"
width = 1920
height = 1080
neighbor.left = "MainPanel"
neighbor.right = "RightPanel"
texture = "lem_right_window.dds"
camera_direction = "forward"
camera_offset_2d.x = 0.576
camera_offset_2d.y = 0.15
camera_offset_2d.z = 1.26

[[panels]]
name = "UpperHatch"
width = 1920
height = 1080
neighbor.down = "EcsPanel"
texture = "lem_upper_hatch_open.dds"
camera_direction = "up"
camera_rotation_polar = 180.0
camera_offset_2d.x = 0.0
camera_offset_2d.y = -0.55
camera_offset_2d.z = 0.0

[[panels]]
name = "RendezvousWindow"
width = 1867
height = 1050
neighbor.up = "DockView"
neighbor.down = "MainPanel"
neighbor.right = "AotPanel"
texture = "lem_rendezvous_window.dds"
camera_direction = "up"
camera_offset_2d.x = -0.598
camera_offset_2d.y = 0.15
camera_offset_2d.z = 1.106

[[panels]]
name = "DockView"
width = 1867
height = 1050
neighbor.down = "RendezvousWindow"
texture = "lem_dock_view.dds"
camera_direction = "up"
fov_override = 30.0
camera_offset_2d.x = -0.598
camera_offset_2d.y = 0.15
camera_offset_2d.z = 1.106

[[panels]]
name = "AotPanel"
width = 1867
height = 1050
neighbor.up = "AotZoom"
neighbor.down = "MainPanel"
neighbor.left = "RendezvousWindow"
texture = "lem_aot_panel.dds"
camera_direction = "forward"
camera_offset_2d.x = 0.0
camera_offset_2d.y = 1.13
camera_offset_2d.z = 1.26

[[panels]]
name = "AotZoom"
width = 1867
height = 1050
neighbor.down = "AotPanel"
texture = "lem_aot_zoom.dds"
camera_direction = "dynamic"
fov_override = 60.0
camera_offset_2d.x = 0.0
camera_offset_2d.y = 1.13
camera_offset_2d.z = 1.26

[[panels]]
name = "ForwardHatch"
width = 1920
height = 1080
neighbor.up = "MainPanel"
texture = "lem_forward_hatch_open.dds"
camera_direction = "forward"
camera_offset_2d.x = 0.0
camera_offset_2d.y = -1.4
camera_offset_2d.z = 1.5